car/urls.py
from django.urls import path

from car import views

app_name = 'car'

urlpatterns = [
     path('create_car/', views.create_car, name='create_car'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('user.urls')),
    path('', include('car.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from home import views

app_name = 'home'

urlpatterns = [
     path('', views.index, name='index'),
]

user/urls.py
from django.urls import path

from user import views

app_name = 'user'

urlpatterns = [
     path('login/', views.auth_login, name='login'),
     path('create_user/', views.create_user, name='create_user'),
     path('logout/', views.logout_user, name='logout'),
     path('profile/', views.profile, name='profile'),
]

car/models.py
from user.models import User
from django.db import models
from datetime import date


class Car(models.Model):
    STATUS_CAR = (
        (1, 'Ativado'),
        (2, 'Desativado'),
        (3, 'Alugado'),
    )

    BRAND = (
        (1, 'Outro'),
        (2, 'Volkswagen'),
        (3, 'Toyota'),
        (4, 'Nissan'),
        (5, 'Ford'),
        (6, 'Honda'),
        (7, 'Hyundai'),
        (8, 'Chevrolet'),
        (9, 'Mercedes-Benz'),
        (10, 'BMW'),
        (11, 'Tesla'),
    )

    COLOR = (
        (1, 'Outra'),
        (2, 'Branco'),
        (3, 'Preto'),
        (4, 'Prata'),
        (5, 'Cinza'),
        (6, 'Vermelho'),
        (7, 'Azul'),
        (8, 'Marrom'),
        (9, 'Verde'),
        (10, 'Amarelo'),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image_car = models.TextField(null=True, blank=True)

    car_model = models.CharField(max_length=255, null=True, blank=False)
    brand = models.PositiveIntegerField(choices=BRAND, null=True, blank=False)
    plaque = models.CharField(max_length=10, null=True, blank=False)
    status_car = models.PositiveIntegerField(choices=STATUS_CAR, null=False)

    color = models.PositiveIntegerField(choices=COLOR, null=False)

    price_day = models.DecimalField(max_digits=6, decimal_places=2)

    initial_date = models.DateField(null=True)
    finish_date = models.DateField(null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'MODELO: {self.car_model} - COR: {self.color}'

    @property
    def days(self):
        return abs((self.finish_date - self.initial_date).days)

    @property
    def is_past_due(self):
        return  date.today() > self.finish_date

home/models.py
from django.db import models

# Create your models here.

user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser, models.Model):
    TYPE_USER = (
        (1, 'Cliente'),
        (2, 'Locatário'),
    )

    username = models.CharField(
        unique=True, max_length=20, null=True, blank=False)
    email = models.CharField(
        unique=True, max_length=20, null=True, blank=False)
    first_name = models.CharField(max_length=50, null=True, blank=False)
    last_name = models.CharField(max_length=50, null=True, blank=False)
    cpf = models.CharField(max_length=11, unique=True,null=True, blank=False)
    address = models.CharField(max_length=255, null=True, blank=True)
    phone = models.CharField(max_length=15)
    type_user = models.IntegerField(choices=TYPE_USER, null=True)
    email = models.EmailField(max_length=254, unique=True)

    REQUIRED_FIELDS = ('username',)
    USERNAME_FIELD = 'email'

    def __str__(self):
        return self.email

car/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from datetime import datetime
from django.db import connection
from django.urls.base import reverse
from django.contrib import messages

from .models import Car


def create_car(request):
    if request.method == 'POST':
        plaque = request.POST.get('plaque')
        car_model = request.POST.get('car_model')
        color = request.POST.get('color')
        image_car = request.POST.get('image_car')
        price_day = request.POST.get('price_day').replace(',', '.')
        brand = request.POST.get('brand')
        image_car = request.POST.get('image_car')
        status_car = request.POST.get('status_car')
        initial_date = request.POST.get('initial_date')
        finish_date = request.POST.get('finish_date')
        created_at = datetime.now()
        updated_at = datetime.now()
        user_id = request.user.id

        with connection.cursor() as cursor:
            cursor.execute("INSERT INTO car_car VALUES(%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)", [
                           None, image_car, car_model, brand, plaque, status_car, color, price_day, initial_date, finish_date,
                           created_at, updated_at, user_id, ])

        messages.success(request, 'Carro cadastrado com sucesso!')
        return HttpResponseRedirect(reverse('user:profile'))

    context = {
        'car_options': Car
    }

    return render(request, 'create_car.html', context)

home/views.py
from django.shortcuts import render, HttpResponse

# Create your views here.


def index(request):
    return render(request, 'home.html', {})

user/views.py
from datetime import datetime
from django.db import connection

from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.hashers import make_password
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.urls import reverse

from user.models import User


def auth_login(request):
    if request.method == 'POST':
        email = request.POST.get('email', None)
        password = request.POST.get('password', None)

        user = authenticate(email=email, password=password)

        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('user:profile'))
            else:
                return HttpResponse('Não foi possível realizar seu login')

    return render(request, 'login.html', {})


def create_user(request):
    if request.method == 'POST':
        username = request.POST.get("username")
        first_name = request.POST.get("first_name")
        email = request.POST.get("email")
        last_name = request.POST.get("last_name")
        phone = request.POST.get("phone")
        cpf = request.POST.get("cpf")
        address = request.POST.get('address')
        type_user = request.POST.get("type_user")
        password = request.POST.get("password1")
        password2 = request.POST.get("password2")
        last_login = datetime.now()
        is_superuser = 0
        is_active = 1
        is_staff = 0
        date_joined = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        if (password2 != password):
            messages.warning(request, 'Senhas não estão iguais')
            return HttpResponseRedirect(reverse('user:create_user'))

        with connection.cursor() as cursor:
            cursor.execute("INSERT INTO user_user VALUES(%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)", [
                None, make_password(
                    password), last_login, is_superuser, is_staff, is_active, date_joined,
                username, first_name, last_name, cpf, address, phone, type_user, email])

        return HttpResponseRedirect(reverse('user:login'))


    context = {
       'user_list': User
    }

    return render(request, 'create_user.html', context)


def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('home:index'))


def profile(request):
    return render(request, 'profile.html', {})

car/templates/create_car.html
{% extends 'index.html' %}
{% block title %} Criar carro {% endblock title %}
{% block sidebar %} {% include 'sidebar.html' %} {% endblock %}
{% block content %} <div id="container">

    <div class="container">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
        {% endif %}

        <div class="row">
            <div id="content" class="col-sm-12">
                <h1 class="title">Adicionar carro</h1>


                <h2 class="subtitle">Novo carro</h2>
                <p><strong>Adicione os dados do carro a ser alugado</strong></p>
                <form action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="row">
                        <div class="form-group col-sm-6">
                            <label class="control-label" for="input-email">Placa do veículo</label>
                            <input type="text" name="plaque" value="" placeholder="Placa do veículo" id="input-email"
                                class="form-control" />
                        </div>

                        <div class="form-group col-sm-6">
                            <label class="control-label" for="input-email">Modelo</label>
                            <input type="text" name="car_model" value="" placeholder="Modelo do carro" id="input-email"
                                class="form-control" />
                        </div>

                        <div class="form-group col-sm-3">
                            <label class="control-label" for="input-email">Preço por dia</label>
                            <input type="textarea" name="price_day" value="" placeholder="Preço por dia"
                                id="input-email" class="form-control" />
                        </div>

                        <div class="form-group col-sm-3">
                            <label>Status do carro</label>
                            <select name="status_car" class="form-control">
                                {% for val, name in car_options.STATUS_CAR %}
                                <option value="{{val}}">{{name}}</option>
                                {% endfor %}
                            </select>
                        </div>

                        <div class="form-group col-sm-3">
                            <label>Cor do carro</label>
                            <select name="color" class="form-control">
                                {% for val, name in car_options.COLOR %}
                                <option value="{{val}}">{{name}}</option>
                                {% endfor %}
                            </select>
                        </div>

                        <div class="form-group col-sm-3">
                            <label>Marca do carro</label>
                            <select name="brand" class="form-control">
                                {% for val, name in car_options.BRAND %}
                                <option value="{{val}}">{{name}}</option>
                                {% endfor %}
                            </select>
                        </div>

                        <div class="form-group col-sm-6">
                            <label class="control-label" for="input-email">Data inicial de aluguel</label>
                            <input type="date" name="initial_date" value="" placeholder="01/06/1998" id="input-email"
                                class="form-control" />
                        </div>

                        <div class="form-group group col-sm-6">
                            <label class="control-label" for="input-email">Data final de aluguel</label>
                            <input type="date" name="finish_date" value="" placeholder="07/06/1998" id="input-email"
                                class="form-control" />
                        </div>

                        <div class="form-group col-sm-12">
                            <label class="control-label" for="input-email">Imagem do carro (URL da imagem)</label>
                            <input type="text" name="image_car" value="" class="form-control" />
                        </div>
                    </div>

                    <input type="submit" value="Criar carro" class="btn btn-primary btn-lg btn-block" />
                    <br>
                </form>

            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}
{% block footer %} {% include 'footer.html' %} {% endblock %}

home/templates/footer.html
 {% load static %}
 <!-- Footer Start -->
 <div class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-3 col-md-6">
                <div class="footer-widget">
                    <h2>Get in Touch</h2>
                    <div class="contact-info">
                        <p><i class="fa fa-map-marker"></i>123 E Store, Los Angeles, USA</p>
                        <p><i class="fa fa-envelope"></i>email@example.com</p>
                        <p><i class="fa fa-phone"></i>+123-456-7890</p>
                    </div>
                </div>
            </div>

            <div class="col-lg-3 col-md-6">
                <div class="footer-widget">
                    <h2>Follow Us</h2>
                    <div class="contact-info">
                        <div class="social">
                            <a href=""><i class="fab fa-twitter"></i></a>
                            <a href=""><i class="fab fa-facebook-f"></i></a>
                            <a href=""><i class="fab fa-linkedin-in"></i></a>
                            <a href=""><i class="fab fa-instagram"></i></a>
                            <a href=""><i class="fab fa-youtube"></i></a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-3 col-md-6">
                <div class="footer-widget">
                    <h2>Company Info</h2>
                    <ul>
                        <li><a href="#">About Us</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                        <li><a href="#">Terms & Condition</a></li>
                    </ul>
                </div>
            </div>

            <div class="col-lg-3 col-md-6">
                <div class="footer-widget">
                    <h2>Purchase Info</h2>
                    <ul>
                        <li><a href="#">Pyament Policy</a></li>
                        <li><a href="#">Shipping Policy</a></li>
                        <li><a href="#">Return Policy</a></li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="row payment align-items-center">
            <div class="col-md-6">
                <div class="payment-method">
                    <h2>We Accept:</h2>
                    <img src="img/payment-method.png" alt="Payment Method" />
                </div>
            </div>
            <div class="col-md-6">
                <div class="payment-security">
                    <h2>Secured By:</h2>
                    <img src="img/godaddy.svg" alt="Payment Security" />
                    <img src="img/norton.svg" alt="Payment Security" />
                    <img src="img/ssl.svg" alt="Payment Security" />
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Footer End -->

<!-- Footer Bottom Start -->
<div class="footer-bottom">
    <div class="container">
        <div class="row">
            <div class="col-md-6 copyright">
                <p>Copyright &copy; <a href="https://htmlcodex.com">HTML Codex</a>. All Rights Reserved</p>
            </div>

            <div class="col-md-6 template-by">
                <p>Template By <a href="https://htmlcodex.com">HTML Codex</a></p>
            </div>
        </div>
    </div>
</div>
<!-- Footer Bottom End -->

home/templates/header.html
{% load static %}
<div class="header">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3">
                <nav class="navbar bg-light">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="#"><i class="fa fa-home"></i>Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#"><i class="fa fa-shopping-bag"></i>Best Selling</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#"><i class="fa fa-plus-square"></i>New Arrivals</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#"><i class="fa fa-female"></i>Fashion & Beauty</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#"><i class="fa fa-child"></i>Kids & Babies Clothes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#"><i class="fa fa-tshirt"></i>Men & Women Clothes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#"><i class="fa fa-mobile-alt"></i>Gadgets & Accessories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#"><i class="fa fa-microchip"></i>Electronics & Accessories</a>
                        </li>
                    </ul>
                </nav>
            </div>
            <div class="col-md-6">
                <div class="header-slider normal-slider">
                    <div class="header-slider-item">
                        <img src="img/slider-1.jpg" alt="Slider Image" />
                        <div class="header-slider-caption">
                            <p>Some text goes here that describes the image</p>
                            <a class="btn" href=""><i class="fa fa-shopping-cart"></i>Shop Now</a>
                        </div>
                    </div>
                    <div class="header-slider-item">
                        <img src="img/slider-2.jpg" alt="Slider Image" />
                        <div class="header-slider-caption">
                            <p>Some text goes here that describes the image</p>
                            <a class="btn" href=""><i class="fa fa-shopping-cart"></i>Shop Now</a>
                        </div>
                    </div>
                    <div class="header-slider-item">
                        <img src="img/slider-3.jpg" alt="Slider Image" />
                        <div class="header-slider-caption">
                            <p>Some text goes here that describes the image</p>
                            <a class="btn" href=""><i class="fa fa-shopping-cart"></i>Shop Now</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="header-img">
                    <div class="img-item">
                        <img src="img/category-1.jpg" />
                        <a class="img-text" href="">
                            <p>Some text goes here that describes the image</p>
                        </a>
                    </div>
                    <div class="img-item">
                        <img src="img/category-2.jpg" />
                        <a class="img-text" href="">
                            <p>Some text goes here that describes the image</p>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

home/templates/home.html
{% extends 'index.html' %}

{% block title %} Home   {% endblock title %}
{% block sidebar  %} {% include 'sidebar.html' %} {% endblock  %}
{% block header  %} {% include 'header.html' %} {% endblock  %}
{% block content  %} {% include 'content.html' %} {% endblock  %}
{% block footer  %} {% include 'footer.html' %} {% endblock  %}

home/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title %} Home {% endblock title %} </title>

     <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400|Source+Code+Pro:700,900&display=swap" rel="stylesheet">


        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
        <link href="{% static 'lib/slick/slick.css' %}" rel="stylesheet">
        <link href="{% static 'lib/slick/slick-theme.css' %}" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans' type='text/css'>
</head>

<body>

    <div class="wrapper-wide">
         {% block sidebar %} {% endblock  %}
        {% block navbar %} {% endblock  %}
        {% block header %} {% endblock  %}
        {% block content %} {% endblock  %}
        {% block footer %} {% endblock  %}
    </div>

    <!--Scripts-->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/slick/slick.min.js' %}"></script>

    <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
</body>

</html>

home/templates/sidebar.html
{% load static %}
<!-- Nav Bar Start -->
<div class="nav">
    <div class="container-fluid">
        <nav class="navbar navbar-expand-md bg-dark navbar-dark">
            <a href="#" class="navbar-brand">MENU</a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                <div class="navbar-nav mr-auto">
                    <a href="index.html" class="nav-item nav-link active">Home</a>
                    <a href="product-list.html" class="nav-item nav-link">Products</a>
                    <a href="product-detail.html" class="nav-item nav-link">Product Detail</a>
                    <a href="cart.html" class="nav-item nav-link">Cart</a>
                    <a href="checkout.html" class="nav-item nav-link">Checkout</a>
                    <a href="my-account.html" class="nav-item nav-link">My Account</a>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">More Pages</a>
                        <div class="dropdown-menu">
                            <a href="wishlist.html" class="dropdown-item">Wishlist</a>
                            <a href="login.html" class="dropdown-item">Login & Register</a>
                            <a href="contact.html" class="dropdown-item">Contact Us</a>
                        </div>
                    </div>
                </div>
                <div class="navbar-nav ml-auto">
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">User Account</a>
                        <div class="dropdown-menu">

                            {% if request.user.id is None %}
                            <a href="{% url 'user:login' %}" class="dropdown-item">Login</a>
                            <a href="{% url 'user:create_user' %}" class="dropdown-item">Registre-se</a>
                            {% else %}
                            <a href="{% url 'user:profile' %}" class="dropdown-item">Perfil</a>
                            <a href="{% url 'user:logout' %}" class="dropdown-item">Sair da conta</a>
                            {% endif %}

                        </div>
                    </div>
                </div>
            </div>
        </nav>
    </div>
</div>
<!-- Nav Bar End -->
<div class="bottom-bar">
    <div class="container-fluid">
        <div class="row align-items-center">
            <div class="col-md-3">
                <div class="logo">
                    <a href="index.html">
                        <img src="img/logo.png" alt="Logo">
                    </a>
                </div>
            </div>
            <div class="col-md-6">
                <div class="search">
                    <input type="text" placeholder="Search">
                    <button><i class="fa fa-search"></i></button>
                </div>
            </div>
            <div class="col-md-3">
                <div class="user">
                    <a href="wishlist.html" class="btn wishlist">
                        <i class="fa fa-heart"></i>
                        <span>(0)</span>
                    </a>
                    <a href="cart.html" class="btn cart">
                        <i class="fa fa-shopping-cart"></i>
                        <span>(0)</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

user/templates/login.html
{% extends 'index.html' %}

{% block title %} Acessar conta {% endblock title %}
{% block sidebar %} {% include 'sidebar.html' %} {% endblock %}
{% block content  %} <div id="container">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{message.tags}}" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    <div class="container">
          <div class="row">
        <!--Middle Part Start-->
        <div id="content" class="col-sm-9">
            <h1 class="title">Fazer login</h1>
            <div class="row">
                <div class="col-sm-6">

                    <form action="" method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label" for="input-email">E-mail</label>
                            <input type="text" name="email" value="" placeholder="E-Mail Address" id="input-email"
                                class="form-control" />
                        </div>
                         <div class="form-group">
                           <div class="form-group">
                            <label class="control-label" for="input-password">Senha</label>
                            <input type="password" name="password" value="" placeholder="Password" id="input-password"
                                class="form-control" />
                        </div>
                        <input type="submit" value="Login" class="btn btn-primary btn-lg btn-block" />
                    </form>

                </div>

            </div>
        </div>
    </div>
    </div>
</div>
{% endblock  %}
{% block footer %} {% include 'footer.html' %} {% endblock %}

user/templates/partials/menu.html
<aside id="column-right" class="col-sm-3 hidden-xs">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col">#</th>
        </tr>
      </thead>
      <tbody>
        {% if request.user.type_user == 2 %}
        <tr>
        <th scope="row"><a href="{% url 'car:create_car' %}">Adicionar novo carro</a></th>
        </tr>
        <tr>
        <th scope="row"><a href="">Carros cadastrados</a></th>
        </tr>
        {% elif request.user.type_user == 1 %}
        <tr>
        <th scope="row"><a href="">Carros Alugados</a></th>
        </tr>
        {% endif %}
      </tbody>
    </table>
  </aside>

user/templates/profile.html
{% extends 'index.html' %}
{% block title %} Perfil -  {{request.user.first_name}}   {% endblock title %}
{% block sidebar %} {% include 'sidebar.html' %} {% endblock %}

{% block content  %}
<div class="container">
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
    {% endif %}
    <div class="row">

        {% block menu  %} {% include 'partials/menu.html' %} {% endblock  %}
        <h3 class="subtitle">Bem vindo, {{user.first_name}}</h3>
    </div>
</div>

{% endblock  %}
{% block footer %} {% include 'footer.html' %} {% endblock %}